Dissplay_django/Boards/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views
from . import views

app_name = 'Boards'

urlpatterns = [
    # base_views.py
    path('board/', base_views.board, name='board'),
    path('board2/', base_views.board2, name='board2'),
    path('board3/', base_views.board3, name='board3'),
    path('board4/', base_views.board4, name='board4'),
    path('board5/', base_views.board5, name='board5'),
    path('question/<int:question_id>/', base_views.detail, name='detail'),
    path('question2/<int:question_id>/', base_views.detail2, name='detail2'),
    path('question3/<int:question_id>/', base_views.detail3, name='detail3'),
    path('question4/<int:question_id>/', base_views.detail4, name='detail4'),
    path('question5/<int:question_id>/', base_views.detail5, name='detail5'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/create/<int:tabnum>/',
         question_views.question_create, name='question_create'),

    # question_modify
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question2/modify/<int:question_id>/',
         question_views.question_modify2, name='question_modify2'),
    path('question3/modify/<int:question_id>/',
         question_views.question_modify3, name='question_modify3'),
    path('question4/modify/<int:question_id>/',
         question_views.question_modify4, name='question_modify4'),
    path('question5/modify/<int:question_id>/',
         question_views.question_modify5, name='question_modify5'),

    # question_delete
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question2/delete/<int:question_id>/',
         question_views.question_delete2, name='question_delete2'),
    path('question3/delete/<int:question_id>/',
         question_views.question_delete3, name='question_delete3'),
    path('question4/delete/<int:question_id>/',
         question_views.question_delete4, name='question_delete4'),
    path('question5/delete/<int:question_id>/',
         question_views.question_delete5, name='question_delete5'),


    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),



    # path('board/', views.board, name='board'),
    # # path('board2/', views.board2, name='board2'),
    # path('board2/', views.board2, name='board2'),
    # path('board3/', views.board3, name='board3'),
    #
    # # path('', views.index, name='index'), # 2-5번
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

]

Dissplay_django/Dissplay/urls.py
from django.contrib import admin
from django.urls import path, include
import Dissplay.views as dv
from Boards.views import base_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('Users/', include('Users.urls')),
    path('Boards/', include('Boards.urls')),
    path('', dv.mainpage, name='mainpage'),
    # path('board1/', dv.board, name='board1'),
    path('', base_views.board2, name='board2'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dissplay_django/Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Users'

urlpatterns=[
    # path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name='login'),
    # path('signup/', views.signup, name='signup'),
    path('signup/', views.signup2, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login2.html'), name='login'),
    path('find_id/', views.find_id, name='find_id'),

]

Dissplay_django/Boards/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to='media/',blank=True, null=True)
    voter = models.ManyToManyField(User,  related_name='voter_question')
    file = models.FileField(upload_to='questions/', blank=True)


    # 추천인 추가

    def __str__(self):
        return self.subject
class Question2(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question2')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User,  related_name='voter_question2')  # 추천인 추가
    file = models.FileField(upload_to='questions2/', blank=True)

    def __str__(self):
        return self.subject

class Question3(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question3')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User,  related_name='voter_question3')  # 추천인 추가
    file = models.FileField(upload_to='questions3/', blank=True)

    def __str__(self):
        return self.subject

class Question4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question4')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question4')  # 추천인 추가
    file = models.FileField(upload_to='questions4/', blank=True)

    def __str__(self):
        return self.subject
class Question5(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question5')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question5')  # 추천인 추가
    file = models.FileField(upload_to='questions5/', blank=True)

    def __str__(self):
        return self.subject
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

Dissplay_django/Boards/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import QuestionForm, AnswerForm
from ..models import Question, Answer

@login_required(login_url='Users:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('Boards:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm
        # return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'Boards/question_detail.html', context)

@login_required(login_url='Users:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('Boards:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('Boards:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'Boards/answer_form.html', context)

@login_required(login_url='Users:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('Boards:detail', question_id=answer.question.id)

@login_required(login_url='Users:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('Boards:detail', question_id=answer.question.id), answer.id))

Dissplay_django/Boards/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question, Question2, Question3, Question4, Question5
from django.db.models import Q

def board(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    print(page_obj)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards1.html", context)

def board2(request):
        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        question_list = Question2.objects.order_by('-create_date')
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
        paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        max_index = len(paginator.page_range)
        context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

        return render(request, "Boards/databoards2.html", context)
def board3(request):
        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        question_list = Question3.objects.order_by('-create_date')
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
        paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        max_index = len(paginator.page_range)
        context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

        return render(request, "Boards/databoards3.html", context)
def board4(request):
    page = request.GET.get('page', '1')  # 페이지
    print('q')
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question4.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else:
        print('h1')

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards4.html", context)

def board5(request):
    page = request.GET.get('page', '1')  # 페이지
    print('q')
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question5.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else:
        print('h1')

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards5.html", context)

### detail ###
def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail.html', context)

def detail2(request, question_id):
    question = get_object_or_404(Question2, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail2.html', context)

def detail3(request, question_id):
    question = get_object_or_404(Question3, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail.html', context)


def detail4(request, question_id):
    question = get_object_or_404(Question4, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail4.html', context)

def detail5(request, question_id):
    question = get_object_or_404(Question5, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail5.html', context)

############# 게시판 ############
# 여기서 긁어왔슴
# def index(request):
#     page = request.GET.get('page', '1')  # 페이지
#     question_list = Question.objects.order_by('-create_date')
#     paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
#     page_obj = paginator.get_page(page)
#     context = {'question_list': page_obj}
#     return render(request, 'Boards/question_list_였던것.html', context)
    # return render(request, 'Boards/databoards4.html', context)

Dissplay_django/templates/Boards/answer_form.html
{% extends 'base.html' %}
{% load static %}
{% load Boards_filter %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Dissplay_django/templates/Boards/question_detail.html
{% extends "base.html" %}
{% load Boards_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    {% if question.file %}
        <img src="{{ question.file.url }}" class="card-img-top" alt="Thumbnail" style="width: 630px; margin-right: 0px">
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
{#                {% if question.modify_date %}#}
{#                <div class="badge bg-light text-dark p-2 text-start mx-3">#}
{#                    <div class="mb-2">modified at</div>#}
{#                    <div>{{ question.modify_date }}</div>#}
{#                </div>#}
{#                {% endif %}#}
{#                <div class="badge bg-light text-dark p-2 text-start">#}
{#                    <div class="mb-2">{{ question.author.username }}</div>#}
{#                    <div>{{ question.create_date }}</div>#}
{#                </div>#}
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'Boards:question_vote' question.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'Boards:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'Boards:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
{#    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>#}
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'Boards:answer_vote' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'Boards:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'Boards:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'Boards:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
{#        <div class="mb-3">#}
{#            <label for="content" class="form-label">답변내용</label>#}
{#            <textarea {% if not user.is_authenticated %}disabled{% endif %}#}
{#              name="content" id="content" class="form-control" rows="10"></textarea>#}
{#        </div>#}
{#        <input type="submit" value="답변등록" class="btn btn-primary">#}
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

Dissplay_django/templates/Boards/question_detail2.html
{% extends "base.html" %}
{% load Boards_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    {% if question.file %}
        <img src="{{ question.file.url }}" class="card-img-top" alt="Thumbnail" style="width: 630px; margin-left: 0px">
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
{#                {% if question.modify_date %}#}
{#                <div class="badge bg-light text-dark p-2 text-start mx-3">#}
{#                    <div class="mb-2">modified at</div>#}
{#                    <div>{{ question.modify_date }}</div>#}
{#                </div>#}
{#                {% endif %}#}
{#                <div class="badge bg-light text-dark p-2 text-start">#}
{#                    <div class="mb-2">{{ question.author.username }}</div>#}
{#                    <div>{{ question.create_date }}</div>#}
{#                </div>#}
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'Boards:question_vote' question.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'Boards:question_modify2' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'Boards:question_delete2' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
{#    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>#}
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'Boards:answer_vote' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'Boards:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'Boards:question_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'Boards:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
{#        <div class="mb-3">#}
{#            <label for="content" class="form-label">답변내용</label>#}
{#            <textarea {% if not user.is_authenticated %}disabled{% endif %}#}
{#              name="content" id="content" class="form-control" rows="10"></textarea>#}
{#        </div>#}
{#        <input type="submit" value="답변등록" class="btn btn-primary">#}
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

Dissplay_django/templates/Boards/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
{#        <div class="mb-3">#}
{#            <label for="thumbnail" class="form-label">Thumbnail:</label>#}
{#            <input type="file" class="form-label" name="file" id="thumbnail"#}
{#                   value="{{ form.thumbnail.value|default_if_none:'' }}">#}
{##}
{#        </div>#}
{#        <div class="mb-3">#}
{#            <label for="file" class="form-label">file:</label>#}
{#            <input type="file" class="form-label" name="file" id="file"#}
{#                   value="{{ form.file.value|default_if_none:'' }}">#}
{#        </div>#}
        <div class="mb-3">
            <label for="file" class="form-label">파일:</label>
            <input type="file" class="form-control" name="file" id="file"
                   value="{{ form.file.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">

            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}