Dissplay_django/Boards/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views
from . import views

app_name = 'Boards'

urlpatterns = [
    # base_views.py
    path('board/', base_views.board, name='board'),
    path('board2/', base_views.board2, name='board2'),
    path('board3/', base_views.board3, name='board3'),
    path('board4/', base_views.board4, name='board4'),
    path('board5/', base_views.board5, name='board5'),
    path('question/<int:question_id>/', base_views.detail, name='detail'),
    path('question2/<int:question_id>/', base_views.detail2, name='detail2'),
    path('question3/<int:question_id>/', base_views.detail3, name='detail3'),
    path('question4/<int:question_id>/', base_views.detail4, name='detail4'),
    path('question5/<int:question_id>/', base_views.detail5, name='detail5'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/create/<int:tabnum>/',
         question_views.question_create, name='question_create'),

    # question_modify
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question2/modify/<int:question_id>/',
         question_views.question_modify2, name='question_modify2'),
    path('question3/modify/<int:question_id>/',
         question_views.question_modify3, name='question_modify3'),
    path('question4/modify/<int:question_id>/',
         question_views.question_modify4, name='question_modify4'),
    path('question5/modify/<int:question_id>/',
         question_views.question_modify5, name='question_modify5'),

    # question_delete
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question2/delete/<int:question_id>/',
         question_views.question_delete2, name='question_delete2'),
    path('question3/delete/<int:question_id>/',
         question_views.question_delete3, name='question_delete3'),
    path('question4/delete/<int:question_id>/',
         question_views.question_delete4, name='question_delete4'),
    path('question5/delete/<int:question_id>/',
         question_views.question_delete5, name='question_delete5'),


    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),



    # path('board/', views.board, name='board'),
    # # path('board2/', views.board2, name='board2'),
    # path('board2/', views.board2, name='board2'),
    # path('board3/', views.board3, name='board3'),
    #
    # # path('', views.index, name='index'), # 2-5번
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

]

Dissplay_django/Dissplay/urls.py
from django.contrib import admin
from django.urls import path, include
import Dissplay.views as dv
from Boards.views import base_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('Users/', include('Users.urls')),
    path('Boards/', include('Boards.urls')),
    path('', dv.mainpage, name='mainpage'),
    # path('board1/', dv.board, name='board1'),
    path('', base_views.board2, name='board2'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dissplay_django/Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Users'

urlpatterns=[
    # path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name='login'),
    # path('signup/', views.signup, name='signup'),
    path('signup/', views.signup2, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login2.html'), name='login'),
    path('find_id/', views.find_id, name='find_id'),

]

Dissplay_django/Boards/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question, Question2, Question3, Question4, Question5
from django.db.models import Q

def board(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    print(page_obj)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards1.html", context)

def board2(request):
        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        question_list = Question2.objects.order_by('-create_date')
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
        paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        max_index = len(paginator.page_range)
        context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

        return render(request, "Boards/databoards2.html", context)
def board3(request):
        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        question_list = Question3.objects.order_by('-create_date')
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()
        paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        max_index = len(paginator.page_range)
        context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

        return render(request, "Boards/databoards3.html", context)
def board4(request):
    page = request.GET.get('page', '1')  # 페이지
    print('q')
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question4.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else:
        print('h1')

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards4.html", context)

def board5(request):
    page = request.GET.get('page', '1')  # 페이지
    print('q')
    kw = request.GET.get('kw', '')  # 검색어

    question_list = Question5.objects.order_by('-create_date')
    print(question_list)
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else:
        print('h1')

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'max_index': max_index}

    return render(request, "Boards/databoards5.html", context)

### detail ###
def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail.html', context)

def detail2(request, question_id):
    question = get_object_or_404(Question2, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail2.html', context)

def detail3(request, question_id):
    question = get_object_or_404(Question3, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail.html', context)


def detail4(request, question_id):
    question = get_object_or_404(Question4, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail4.html', context)

def detail5(request, question_id):
    question = get_object_or_404(Question5, id=question_id)
    context = {'question': question}
    return render(request, 'Boards/question_detail5.html', context)

############# 게시판 ############
# 여기서 긁어왔슴
# def index(request):
#     page = request.GET.get('page', '1')  # 페이지
#     question_list = Question.objects.order_by('-create_date')
#     paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
#     page_obj = paginator.get_page(page)
#     context = {'question_list': page_obj}
#     return render(request, 'Boards/question_list_였던것.html', context)
    # return render(request, 'Boards/databoards4.html', context)

Dissplay_django/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- Dissplay CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'signin.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup.css' %}">

    <title>🖥️Dissplay🖥️</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<!-- 기본 템플릿 안에 삽입될 내용 End -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

Dissplay_django/templates/mainpage.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<title>🖥️Display🖥️</title>
<style>
    .link {
        font-size: 24px;
    }
    .slideshow-container {
        position: relative;
        max-width: 2000px center;
        height: 900px;
        margin: auto;
        overflow: hidden;
    }
{#<!--    슬라이드쇼 컨테이너-->#}
    .slide {
        position: absolute;
        top: 0;
        left: 0;
        opacity: 0;
        transition: opacity 1s ease-in-out;
    }
{#<!--    슬라이드-->#}
    .slide.active {
        opacity: 1;
    }
{#<!--    투명도-->#}
</style>
<script>
    window.addEventListener('DOMContentLoaded', function() {
        var slides = document.querySelectorAll('.slide');
        var index = 0;

        function showNextSlide() {
            slides[index].classList.remove('active');
            index = (index + 1) % slides.length;
            slides[index].classList.add('active');
        }

        var interval = 3000;
        setInterval(showNextSlide, interval);
    });
  // 페이지 로드가 완료되면 실행되는 함수
  // 모든 슬라이드 요소를 선택하여 배열로 가져옵니다.
  // 현재 활성화된 슬라이드의 인덱스를 나타내는 변수를 초기화합니다.
  // 다음 슬라이드를 보여주는 함수
  // 현재 활성화된 슬라이드에서 'active' 클래스를 제거하여 화면에서 사라지게 합니다.
  // 인덱스를 다음 슬라이드로 업데이트합니다. 배열의 길이를 넘어가면 다시 첫 번째 슬라이드로 돌아갑니다.
  // 새로운 현재 슬라이드에 'active' 클래스를 추가하여 화면에 나타나게 합니다.
   // 슬라이드 전환 간격을 3초로 설정합니다.
   // 일정한 간격으로 showNextSlide 함수를 실행하여 다음 슬라이드를 보여줍니다.
</script>

<div class="slideshow-container" >
    <div class="slide active">
        <img src="{% static 'Background2.png' %}" alt="" width="2000" height="900">
    </div>
    <div class="slide">
        <img src="{% static 'wafer.jpeg' %}" alt="" width="2000" height="900">
    </div>
    <div class="slide">
        <img src="{% static 'Background3.jpg' %}" alt="" width="2000" height="900">
    </div>
</div>
{% endblock %}

Dissplay_django/templates/navbar.html
{% load static %}
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
       <a href="{% url 'mainpage' %}">
        <img  src="{% static 'dissplaylogo.png' %}" alt="" width="80" height="80">
       </a>
           <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Users:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'Users:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Users:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Boards:board' %}">개요</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Boards:board2' %}">UCI SECOM</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Boards:board3' %}">Wafer 811k</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'Boards:board4' %}">결론</a>
                    {% endif %}
                </li>
{#                <li>#}
{#                    {% if user.is_authenticated %}#}
{#                    <a class="nav-link" href="{% url 'Boards:board5' %}">게시판5</a>#}
{#                    {% endif %}#}
{#                </li>#}
            </ul>
        </div>
    </div>
</nav>