datos/datos/urls.py
from django.urls import path

# from . import views
from .views import base_views, question_views, answer_views


app_name = 'datos'

urlpatterns = [
     # base_views.py
     path('',
          base_views.index, name='index'),
     path('<int:question_id>/',
          base_views.detail, name='detail'),

     # question_views.py
     path('question/create/<int:tabnum>/',
          question_views.question_create, name='question_create'),
     path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
     path('question/delete/<int:question_id>/',
          question_views.question_delete, name='question_delete'),

     # answer_views.py
     path('answer/create/<int:question_id>/',
          answer_views.answer_create, name='answer_create'),
     path('answer/modify/<int:answer_id>/',
          answer_views.answer_modify, name='answer_modify'),
     path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
     path('question/vote/<int:question_id>/', 
          question_views.question_vote, name='question_vote'),
     path('answer/vote/<int:answer_id>/', 
          answer_views.answer_vote, name='answer_vote'),
]

datos/datos/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


#
# class Question2(Question):
#     pass
#
# class Question3(Question):
#     pass
#
# class Question4(Question):
#     pass


class Question2(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question2')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question2')  # 추천인 추가

    def __str__(self):
        return self.subject


class Question3(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question3')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question3')  # 추천인 추가

    def __str__(self):
        return self.subject


class Question4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question4')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    content2 = models.TextField(default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)   # 어떤조건이든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question4')  # 추천인 추가

    def __str__(self):
        return self.subject

datos/datos/forms.py
from django import forms
from datos.models import Question, Answer, Question2, Question3, Question4

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'content2']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
            'content2': '내용2',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }


class QuestionForm2(forms.ModelForm):
    class Meta:
        model = Question2  # 사용할 모델
        fields = ['subject', 'content', 'content2']  # QuestionForm에서 사용할 Question 모델의 속성

        labels = {
            'subject': '제목',
            'content': '내용',
            'content2': '내용2',
        }

class QuestionForm3(forms.ModelForm):
    class Meta:
        model = Question3  # 사용할 모델
        fields = ['subject', 'content', 'content2']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
            'content2': '내용2',
        }
class QuestionForm4(forms.ModelForm):
    class Meta:
        model = Question4  # 사용할 모델
        fields = ['subject', 'content', 'content2']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
            'content2': '내용2',
        }

datos/datos/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')   # 어노테이션 함수, 자동으로 로그인 화면으로 이동
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            #return redirect('datos:detail', question_id=question.id)
            return redirect('{}#answer_{}'.format(
                resolve_url('datos:detail', question_id=question.id), answer.id))
        
    else:
        # return HttpResponseNotAllowed('Only POST is possible.')
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'datos/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('datos:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            #eturn redirect('datos:detail', question_id=answer.question.id)
            return redirect('{}#answer_{}'.format(
                resolve_url('datos:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'datos/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('datos:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    #return redirect('datos:detail', question_id=answer.question.id)
    return redirect('{}#answer_{}'.format(
                    resolve_url('datos:detail', question_id=answer.question.id), answer.id))

datos/datos/views/base_views.py
from django.core.paginator import Paginator  
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.db.models import Q, Count


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')

    # question_list = Question.objects.order_by('-create_date')

    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')


    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 4)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {'question_list': page_obj, 'max_index': max_index, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'datos/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'datos/question_detail.html', context)

datos/datos/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm, QuestionForm2, QuestionForm3, QuestionForm4

from ..models import Question, Question2, Question3

@login_required(login_url='common:login')   # 어노테이션 함수, 자동으로 로그인 화면으로 이동
def question_create(request, tabnum):
    if request.method == 'POST':
        temp_post = request.POST
        str_direct = ''
        if tabnum == 1 :
            form = QuestionForm(temp_post)
            str_direct = 'datos:index'
        elif tabnum == 2 :
            form = QuestionForm2(temp_post)
            str_direct = 'common:cctv'
        elif tabnum == 3 :
            form = QuestionForm3(temp_post)
            str_direct = 'common:population'
        elif tabnum == 4 :
            form = QuestionForm4(temp_post)
            str_direct = 'common:conclusion'

        if form.is_valid():
            question = form.save(commit=False) # 임시 저장하여 question 객체를 리턴받는다.
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now() # 실제 저장을 위해 작성일시를 설정한다.
            question.save()  # 데이터를 실제로 저장한다.
            return redirect(str_direct)
    else:
        # 202300509_kkh 시작
        # form = QuestionForm() if tabnum == 1 else (QuestionForm2() if tabnum == 2  else (QuestionForm3() if tabnum == 3  else QuestionForm4()))
        # 202300509_kkh 끝
        if tabnum == 1 :
            form = QuestionForm()
        elif tabnum == 2 :
            form = QuestionForm2()
        elif tabnum == 3 :
            form = QuestionForm3()
        elif tabnum == 4 :
            form = QuestionForm4()
    context = {'form': form, 'tabnum' : tabnum}
    return render(request, 'datos/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('datos:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('datos:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'datos/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('datos:detail', question_id=question.id)
    question.delete()
    return redirect('datos:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('datos:detail', question_id=question.id)

datos/templates/datos/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

datos/templates/datos/question_detail.html
{% extends 'base.html' %}
{% load datos_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <!-- <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div> -->
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                    {#  글 옆에 시간 작성자랑 시간표시되는 부분   #}
{#                <div class="badge bg-light text-dark p-2" text-start>#}
{#                    <div class="mb-2">{{ question.author.username }}</div>#}
{#                    <div>{{ question.create_date }}</div>#}
{#                </div>#}
            </div>
            <div class="my-3">
{#                <a href="javascript:void(0)" data-uri="{% url 'datos:question_vote' question.id  %}"#}
{#               class="recommend btn btn-sm btn-outline-secondary"> 추천#}
{#                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>#}
{#                </a>#}
                {% if request.user == question.author %}
                <a href="{% url 'datos:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                   <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'datos:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>



    <div class="card my-3">
        <div class="card-body">
            <!-- <div class="card-text" style="white-space: pre-line;">{{ question.content2 }}</div> -->
            <div class="card-text">{{ question.content2|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                    {#  글 옆에 시간 작성자랑 시간표시되는 부분   #}
{#                <div class="badge bg-light text-dark p-2" text-start>#}
{#                    <div class="mb-2">{{ question.author.username }}</div>#}
{#                    <div>{{ question.create_date }}</div>#}
{#                </div>#}
            </div>
            <div class="my-3">
{#                <a href="javascript:void(0)" data-uri="{% url 'datos:question_vote' question.id  %}"#}
{#               class="recommend btn btn-sm btn-outline-secondary"> 추천#}
{#                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>#}
{#                </a>#}
                {% if request.user == question.author %}
                <a href="{% url 'datos:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                   <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'datos:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
{#    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>#}
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <!-- <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div> -->
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
            {% endif %}
                <div class="badge bg-light text-dark p-2" text-start>
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'datos:answer_vote' answer.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'datos:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                   <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'datos:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'datos:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
         <!-- 오류표시 Start -->
         {% if form.errors %}
         <div class="alert alert-danger" role="alert">
             {% for field in form %}
             {% if field.errors %}
             <div>
                 <strong>{{ field.label }}</strong>
                 {{ field.errors }}
             </div>
             {% endif %}
             {% endfor %}
         </div>
         {% endif %}
         <!-- 오류표시 End --> 
{#        <div class="mb-3">#}
{#            <label for="content" class="form-label">답변내용</label>#}
{#            <textarea {% if not user.is_authenticated %}disabled{% endif %}#}
{#              name="content" id="content" class="form-control" rows="10"></textarea>#}
{#            <textarea name="content" id="content" class="form-control" rows="10"></textarea>#}
{#        </div>#}
{#        <input type="submit" value="답변등록" class="btn btn-primary">#}
    </form>
</div>  
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

datos/templates/datos/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" action="{% url 'datos:question_create' tabnum=tabnum %}">
{#    <!-- <form method="post" action="{% url 'datos:question_create' %}"> -->#}
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="content2" class="form-label">내용2</label>
            <textarea class="form-control" name="content2"
                      id="content2" rows="10">{{ form.content2.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

datos/templates/datos/question_list.html
{% extends 'base.html' %}
{% load static %}
{% load datos_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
<!-- 정렬조건 추가 -->
{#        <div class="col-2">#}
{#            <select class="form-control so">#}
{#                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>#}
{#                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>#}
{#                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>#}
{#            </select>#}
{#        </div>#}
<!-- 정렬조건 추가 끝-->
    </div>
    <table class="table my-4">
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center py-4">
            <td class="text-start" style="border:0;">
                <div class="card_wrapper my-5">
                    <div class="card rounded-3 shadow border-light hover-effect" style="width:30rem;margin:0 auto;">
                        <!-- static 태그 내부에서는 변수 사용 불가 -> {% get_static_prefix %}를 이용해 절대경로로 접근하면 변수 사용 가능 -->
                        <!-- 변수로 question.id를 사용했을 때 삭제 등의 이유로 id가 1씩 순차적으로 늘어나지 않아서 paginator의 인덱스를 사용하여 이미지를 변경-->
                        <!-- 추후에 논의를 통해 이미지의 제목과 게시글의 제목을 일치시켜서 question.subject로 이미지 접근 하는 방식을 적용하는 방안에 대해 생각 해봐도 좋을 것 같음 -->
                        <img src="{% get_static_prefix %}img/img{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}.png" class="card-img-top" alt="img{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}.png" style="margin:0 auto;">
                        <div class="card-body border-top py-1">
                            <a class="d-block text-start text-dark fs-5 my-4" href="{% url 'datos:detail' question.id %}" style="text-decoration:none;">
                            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }} : {{ question.subject }}
                            </a>
                            <p class="text-end create_date fs-6 py-2" style="color: #696969;">{{ question.create_date|date_format }}</p>
<!--                    <p class="card-text"></p>-->
                        </div>
                    </div>
                </div>

<!--                <div>-->
<!--                    <div></div><a href="{% url 'datos:detail' question.id %}">썸네일</a><div><br>-->
<!--                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }} :-->
<!--                    <a href="{% url 'datos:detail' question.id %}">{{ question.subject }}</a>-->
<!--                    {% if question.answer_set.count > 0 %}-->
<!--                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>-->
<!--                    {% endif %}-->
<!--                </div>-->
            </td>
<!--{#            <td>{{ question.author.username }}</td>  &lt;!&ndash; 글쓴이 추가 &ndash;&gt;#}-->
<!--{#            <td>{{ question.create_date }}</td>#}-->
        </tr>
        {% endfor %}
        {% else %}
        <tr>질문이 없습니다.</tr>
        {% endif %}
        </tbody>
    </table>
        <div class="row my-3 pt-4 pb-2">
            <div class="col-2">
                <a href="{% url 'datos:question_create' tabnum=1 %}" class="btn btn-dark bg-gradient shadow-sm">게시물 추가</a>
            </div>
            <div class="col-10">
                <div class="input-group">
                    <input type="text" id="search_kw" class="form-control bg-gradient border-0 mx-1 rounded-1 shadow-sm" value="{{ kw|default_if_none:'' }}" style="background-color:#eaeaea;">
                    <div class="input-group-append">
                        <button class="btn btn-outline-dark shadow-sm" type="button" id="btn_search">찾기</button>
                    </div>
                </div>
            </div>
        </div>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center pb-2">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a> -->
            <a class="page-link text-dark border-light shadow-sm" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link border-light shadow-sm" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link bg-dark bg-gradient border-secondary  shadow-sm" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link text-dark border-light shadow-sm" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link text-dark border-light  shadow-sm" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
            <!-- <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a> -->
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link shadow-sm" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
{#    <a href="{% url 'datos:question_create' %}" class="btn btn-primary">질문 등록하기</a>#}
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
</script>
{% endblock %}